# Generated by Django 5.2.17 on 2026-09-11 12:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaItem',
            fields=[
                ('id_categoria_item', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'categoria de item',
                'verbose_name_plural': 'categorias de item',
                'db_table': 'categoria_item',
            },
        ),
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id_doador', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'doador',
                'verbose_name_plural': 'doadores',
                'db_table': 'doador',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id_familia', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_responsavel', models.CharField(max_length=150)),
                ('endereco', models.TextField()),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('num_membros', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'família',
                'verbose_name_plural': 'famílias',
                'db_table': 'familia',
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id_unidade_medida', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('sigla', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'unidade de medida',
                'verbose_name_plural': 'unidades de medida',
                'db_table': 'unidade_medida',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
                ('perfil', models.CharField(choices=[('administrador', 'Administrador'), ('voluntario', 'Voluntário')], max_length=15)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoriaitem')),
                ('unidade_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unidademedida')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'itens',
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id_doacao', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('data', models.DateField()),
                ('cancelado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.doador')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.item')),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doacoes_canceladas', to='core.usuario')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doacoes_registradas', to='core.usuario')),
            ],
            options={
                'verbose_name': 'doação',
                'verbose_name_plural': 'doações',
                'db_table': 'doacao',
            },
        ),
        migrations.CreateModel(
            name='Distribuicao',
            fields=[
                ('id_distribuicao', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('data', models.DateField()),
                ('cancelado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.familia')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.item')),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribuicoes_canceladas', to='core.usuario')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribuicoes_registradas', to='core.usuario')),
            ],
            options={
                'verbose_name': 'distribuição',
                'verbose_name_plural': 'distribuições',
                'db_table': 'distribuicao',
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['unidade_medida'], name='idx_item_id_unidade'),
        ),
        migrations.AddIndex(
            model_name='doacao',
            index=models.Index(fields=['item'], name='idx_doacao_id_item'),
        ),
        migrations.AddIndex(
            model_name='doacao',
            index=models.Index(fields=['doador'], name='idx_doacao_id_doador'),
        ),
        migrations.AddIndex(
            model_name='doacao',
            index=models.Index(fields=['data'], name='idx_doacao_data'),
        ),
        migrations.AddIndex(
            model_name='distribuicao',
            index=models.Index(fields=['item'], name='idx_dist_id_item'),
        ),
        migrations.AddIndex(
            model_name='distribuicao',
            index=models.Index(fields=['familia'], name='idx_dist_id_familia'),
        ),
        migrations.AddIndex(
            model_name='distribuicao',
            index=models.Index(fields=['data'], name='idx_dist_data'),
        ),
    ]
