# Generated by Django 5.2.17 on 2026-09-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='senha_hash',
            field=models.CharField(db_column='senha_hash', max_length=255),
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='senha_hash',
            new_name='password',
        ),
    ]
