# Generated by Django 5.2.17 on 2026-09-24 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_usuario_senha_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="estoque_minimo",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
